# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-28 02:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_posts_pub_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='update_date',
        ),
    ]
