# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-30 04:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20170830_0504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='title',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
