# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-30 05:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20170830_0524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='username',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
