# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-01 18:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20170830_0614'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posts',
            options={'ordering': ['-pub_date']},
        ),
        migrations.AddField(
            model_name='posts',
            name='updated',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='posts',
            name='pub_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
