# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-28 03:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Publisher',
        ),
    ]
