# Generated by Django 2.0 on 2017-12-31 06:59

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20170910_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='prof_image',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to=account.models.upload_location, width_field='width_field'),
        ),
    ]
