# Generated by Django 2.0 on 2017-12-31 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_profile_prof_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
    ]
