# Generated by Django 2.0.1 on 2018-01-10 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_profile_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='slug',
            new_name='user_url',
        ),
    ]
