# Generated by Django 2.0 on 2018-01-10 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_auto_20180110_2048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user_url',
        ),
    ]
